{"uuid": "561f36f3-b45e-46db-97c5-721e2ee66ae7", "children": ["a679a456-99e0-4e5d-b301-c6f99be7d82f", "a6c48621-5939-4fb9-9e0a-b4ff6e6b9ec4", "cba252fa-fbab-46df-893f-949d2154d8cc", "33b8ebad-280e-43da-a148-5bc5ea08ad28", "5965910d-dead-4fc3-83d5-2e343c5c261c", "f124bf9a-1643-4d82-8595-ab39cabfc022", "2e48cbda-e5e3-4668-b820-7b7a5fefd485", "2f5c566a-ed00-48bb-be70-c91e06ab1f5b", "09495169-e14f-4f81-bdc4-38cfb09b844f", "9ce660d7-29e9-4723-a551-5377eee7657b", "e83bb52a-023e-4a5b-865d-013146c80355", "62731019-e229-41a5-80ee-55164ef0d98f", "f0702dce-99f7-4d47-8b87-6c54c4090bc4", "a59aa411-3c21-4a51-8e2c-078c875297b9", "40e9c270-ba8f-44e9-8780-1d1251657ab2", "c5a56cc5-6ac9-4d62-b040-77d55f7db21e", "e3f83afd-e3b9-4f15-be3f-3b2c8b8839a1", "4e9225a0-3159-4f4e-b585-490090a15dde"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to 'normal', current state is 'maximized'\n  (Session info: chrome=92.0.4515.159)\n\n", "trace": "  File \"/home/bipin/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/bipin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/bipin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/bipin/YIPL/Automation/PBMIS/testCases/conftest.py\", line 21, in setup\n    driver.set_window_position(0,0)\n  File \"/home/bipin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1131, in set_window_position\n    return self.set_window_rect(x=int(x), y=int(y))\n  File \"/home/bipin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1180, in set_window_rect\n    return self.execute(Command.SET_WINDOW_RECT, {\"x\": x, \"y\": y,\n  File \"/home/bipin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/home/bipin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1629275384275, "stop": 1629275385847}], "start": 1629275384275, "stop": 1629275386386}